### ISSUE TITLE
Request to be a part of this game development

### ISSUE THREAD

**Issue by jeffreytjs** [Deep-Fold/CatapultGame#1]
Hi, I am Jeffrey and I came across your game in the Game Off 2020 a few days back. I have to say that I'm very impressed by the artwork and the somewhat simplistic syntax of Godot. I love the game but felt that it ended too quickly and there is currently no persistency across games, that's why I feel like diving into the code and see if I could contribute to build the game a little more.

Just wondering if you have existing plans to develop this game further and if so, may I be a part of it? But I have no experience in Godot nor game development, the similarity to python has piqued my interest to dabble in it a little. This would be a great opportunity for me to pick up Godot and be able to apply directly. 

In the case that you are not intending to work on it, would you like to propose a license that I am able to adhere to? I'm only looking to host it on GitHub pages for my own testing and maybe pass around to some of my friends if I eventually manage to make some tweaks or additional features on top of your work. I would very much like to credit you for the idea and initial codebase on the various interfaces as necessary. 

Hope to hear from you soon.

**Comment by Deep-Fold** [comment]
Hey, thanks for checking out the game!

I do have plans to expand on the current game, including persistence. That's something that I want to do solo though.

However, that doesn't mean you can't change it in your own way. You can copy/fork the repo and change it however you like. 
As long as you give credit, release the project open-source and it's non-commercial I'm fine with it (so basically CC BY-NC 3.0 license). Keep in mind however that the songs are from Kevin MacLeod and have their own license attached to them.

Hope that answers your question, good luck!

**Comment by jeffreytjs** [comment]
Thanks for the response!

I'm really glad that you are looking to expand on the game, and I respect that you want to do solo. In this case, I would copy the repo instead of forking it. Yes, I plan to provide credit at the top of the repo readme and even the game itself (if I get to the point where I can add texts within the game). It will be open-source and I'll keep to the same license. Thanks for the heads up on the songs too, I'll see how I can work this license thing out. Not too experienced but I'll be sure to read up.

Your response has been helpful, I'll check back once in awhile and ping you once I set it up including the credit to you. If it's okay with you, I would like to close this issue after I set it up and let you have a quick look to make sure the crediting is done right.

**Comment by Deep-Fold** [comment]
Sounds good to me.

**Comment by jeffreytjs** [comment]
Hi @Deep-Fold, the repo is up and accessible on https://github.com/jeffreytjs/Catapult-Godot. If there's anything else you would like to include do let me know, thanks once again. Cheers. 💯

**Comment by Deep-Fold** [comment]
Okay looks good, really cool that you want to expand on the game. Let me know if you want something explained about the code/other stuff. Closing this issue now.
